# carbon sequestration using Siegel et al 2021 results
# of fraction of CO2 retention after 100 years

# Figure S2A: at study site, retention after 100 years at an injection depth
# of 200 m is 4.8%. See model output from Siegel et 2021 
# (FracSeqAtPAP_funcZandT_HM_calculations.csv from Dave Siegel). 

# Figure S2B: at study site, retention after 100 years at an injection depth 
# of 530 m is 0.017, or 1.7%, but we'll stick with just 200 m for the manuscript
# (most fish carbon flux studies look at C transport out of euphotic zone or to 200 m, 
# not 500)

# For the purposes of this thought experiment, we will use the min and max fish flux
# estimate at a flux boundary of approximately 200 m and 500 m. Approximately 
# 0-10% of carbon that is released at these depths will be retained for 100 
# years (Siegel et al. 2021, Fig. S2A and S2B). If we assume that fecal pellet 
# (egestion) flux, mortality flux, and excretion flux will sink to the seafloor or at least 1000s of meters,
# rather than becoming remineralized at the depth where it was released, then 
# we find the amount sequestered as shown below
# (see Siegel et al. 2021, Supplementary Figure S2C). 

# use inner 90th percentiles as min/max C flux estimates 


## Carbon transport calculations ## 

# need to find: 

# 1) max estimated VM respiratory flux at 200 m
# 2) min estimated VM egestion, excretion and mortality flux at 200 m
# 3) max estimated VM egestion, excretion and mortality flux at 200 m

# 4) max estimated NM respiratory flux at 200 m 
# 5) min estimated NM egestion, excretion and mortality flux at 200 m 
# 6) max estimated NM egestion, excretion and mortality flux at 200 m



# Run 01-calc_c_flux script (to load functions and assign object "nl" below)
source("code/01-calc_c_flux.R")

# uses get_pars() function to make a data frame containing nsims parameter
# draws, for bioenergetic and movement parameters only (generated in chapter 1) 
pars_df <- get_pars(nsims = 1000)

# now turn the current row of the data frame into a list.
# transpose, then rename each row (each par) as an item in the list becuase
# the function make_tau() requires a list.
# later turn row "1" into "i" in a loop
pars.draw.i.df <- t(pars_df[1,]) # later, make 1 into an i
pars.draw.i <- setNames(split(pars.draw.i.df, seq(nrow(pars.draw.i.df))), rownames(pars.draw.i.df))


#### Find C flux at study site for each nsims, VM fish ####
# Produce a df that gives the par draws (bioenergetic/movement pars, q, cal, and catch)
# as well as associated C flux at the study site for each of nsims iterations
# (this df will be needed for plotting)

# for VM fish only. define nsims and make empty vectors for catch (C_t_bar_nsims)
# capture efficiency (q_nsims), calibration factor correction (cal_nsims), 
# carbon flux for each length increment (tau_l), and carbon flux (C_flux_site_nsims)
nsims = 1000
pars_df <- get_pars(nsims = nsims)
C_t_bar_nsims <- rep(NA, times = nsims)
q_nsims <- rep(NA, times = nsims)
cal_nsims <- rep(NA, times = nsims)
C_flux_site_nsims <- rep(NA, times = nsims)
tau_l <- rep(NA, times = nl) # nl has already been generated above

for (i in 1:nsims){
  # for Monte Carlo analysis: add new column to MC_results_VM with C flux at study site (step 11 below)
  
  # step 2 above: load data
  thedata <- load_data()
  fishdata <- thedata[[1]]
  volumedata <- thedata[[2]]
  
  # step 3 above: choose taxon
  taxagroup <- "Myctophidae"
  
  # step 4 above: assign parameters (does not include q and catch)
  pars.draw.i.df <- t(pars_df[i,])
  pars.draw.i <- setNames(split(pars.draw.i.df, seq(nrow(pars.draw.i.df))),
                          rownames(pars.draw.i.df))
  
  # step 5 above: filter data by taxon group
  taxadata <- dplyr::filter(thedata[[1]], Family == taxagroup)
  
  # step 6 above: calculate length bins and P(l)
  # P(l) is the probability of fish being in each length bin
  Pl_and_l <- make_Pl(taxadata$Std_length_mm)
  
  nl <- length(Pl_and_l$L)
  
  # step 7 above: For each L, calculate tau (total carbon flux for that length fish)

  #instead of using the first value [1] 
  # generated by make_tau(), we will use only the sum of values [4], [5], and [6],
  # which are the egestion, excretion and mortality fluxes, respectively. See the last few lines
  # of C.flux.function.VM code for more details on how this function works. 
  for (j in 1:nl) {
    tau_l[j] <- make_tau(L = Pl_and_l$L[j], pars = pars.draw.i, taxagroup = taxagroup, VM = TRUE, lwreg)[4] + 
      make_tau(L = Pl_and_l$L[j], pars = pars.draw.i, taxagroup = taxagroup, VM = TRUE, lwreg)[5] + 
      make_tau(L = Pl_and_l$L[j], pars = pars.draw.i, taxagroup = taxagroup, VM = TRUE, lwreg)[6]
  }
  
  # step 8 above: Multiply P(L) times tau_l and sum
  ind_C_flux <- sum(tau_l * Pl_and_l$P)
  
  # step 9 above: find average of all tows, but instead of using tows from
  # the data with calc_C_t_bar() like we did for nominal par calculation, 
  # now use make_random_catch() to draw tows from the PDF for catches
  C_t <- make_random_catch(fishdata = fishdata, volumedata = volumedata, 
                           towlist = c(2, 4, 6, 8, 9, 11, 48, 90), group = "Myctophidae")
  C_t_bar <- mean(C_t) # average across all simulated catches
  C_t_bar_nsims[i] <- C_t_bar
  
  # step 10 above: calculate n_g for VM fish 
  # n_g = number of fish of that taxonomic group, based now on a simulated C_t_bar for myctophids
  # generate a random draw for capture efficiency for this single set of pars
  q <- runif(n = 1, min = 0.05, max = 0.50)
  q_nsims[i] <- q
  cal <- runif(n = 1, min = 1, max = 1.5)
  cal_nsims[i] <- cal
  n_g_myct <- calc_n_g(catch = C_t_bar_nsims[i], capture_efficiency = q_nsims[i], cal = cal_nsims[i])
  
  # step 11 above: calculate C flux for VM fish and (new for MC analysis) add to MC_results_VM df
  C_flux_site_nsims[i] <- ind_C_flux * n_g_myct 
}

MC_results_VM_eg_ex_mort <- cbind(pars_df, C_t_bar_nsims, q_nsims, cal_nsims, C_flux_site_nsims)



# repeat for VM fish but now for respiratory flux (resp and SDA fluxes)

C_t_bar_nsims <- rep(NA, times = nsims)
q_nsims <- rep(NA, times = nsims)
cal_nsims <- rep(NA, times = nsims)
C_flux_site_nsims <- rep(NA, times = nsims)
tau_l <- rep(NA, times = nl) # nl has already been generated above

for (i in 1:nsims){
  # for Monte Carlo analysis: add new column to MC_results_VM with C flux at study site (step 11 below)
  
  # step 2 above: load data
  thedata <- load_data()
  fishdata <- thedata[[1]]
  volumedata <- thedata[[2]]
  
  # step 3 above: choose taxon
  taxagroup <- "Myctophidae"
  
  # step 4 above: assign parameters (does not include q and catch)
  pars.draw.i.df <- t(pars_df[i,])
  pars.draw.i <- setNames(split(pars.draw.i.df, seq(nrow(pars.draw.i.df))),
                          rownames(pars.draw.i.df))
  
  # step 5 above: filter data by taxon group
  taxadata <- dplyr::filter(thedata[[1]], Family == taxagroup)
  
  # step 6 above: calculate length bins and P(l)
  # P(l) is the probability of fish being in each length bin
  Pl_and_l <- make_Pl(taxadata$Std_length_mm)
  
  nl <- length(Pl_and_l$L)
  
  # step 7 above: For each L, calculate tau (total carbon flux for that length fish)
  
  #instead of using the first value [1] 
  # generated by make_tau(), we will use only the sum of values [4], [5], and [6],
  # which are the egestion, excretion and mortality fluxes, respectively. See the last few lines
  # of C.flux.function.VM code for more details on how this function works. 
  for (j in 1:nl) {
    tau_l[j] <- make_tau(L = Pl_and_l$L[j], pars = pars.draw.i, taxagroup = taxagroup, VM = TRUE, lwreg)[2] + 
      make_tau(L = Pl_and_l$L[j], pars = pars.draw.i, taxagroup = taxagroup, VM = TRUE, lwreg)[3] 
    }
  
  # step 8 above: Multiply P(L) times tau_l and sum
  ind_C_flux <- sum(tau_l * Pl_and_l$P)
  
  # step 9 above: find average of all tows, but instead of using tows from
  # the data with calc_C_t_bar() like we did for nominal par calculation, 
  # now use make_random_catch() to draw tows from the PDF for catches
  C_t <- make_random_catch(fishdata = fishdata, volumedata = volumedata, 
                           towlist = c(2, 4, 6, 8, 9, 11, 48, 90), group = "Myctophidae")
  C_t_bar <- mean(C_t) # average across all simulated catches
  C_t_bar_nsims[i] <- C_t_bar
  
  # step 10 above: calculate n_g for VM fish 
  # n_g = number of fish of that taxonomic group, based now on a simulated C_t_bar for myctophids
  # generate a random draw for capture efficiency for this single set of pars
  q <- runif(n = 1, min = 0.05, max = 0.50)
  q_nsims[i] <- q
  cal <- runif(n = 1, min = 1, max = 1.5)
  cal_nsims[i] <- cal
  n_g_myct <- calc_n_g(catch = C_t_bar_nsims[i], capture_efficiency = q_nsims[i], cal = cal_nsims[i])
  
  # step 11 above: calculate C flux for VM fish and (new for MC analysis) add to MC_results_VM df
  C_flux_site_nsims[i] <- ind_C_flux * n_g_myct 
}

MC_results_VM_resp <- cbind(pars_df, C_t_bar_nsims, q_nsims, cal_nsims, C_flux_site_nsims)


#### Repeat MC analysis for NM fish ####
# change make_tau argument "VM" from
# TRUE to FALSE and to change taxagroup from Myctohpidae to Gonostomatidae

# changing argument VM from TRUE to false will change the H predctor 
# (habitat depth in modified Ikeda 2016 regression) from 1 to 0

# use same parameter values as used for VM fish where possible, 
# so that parameters that should be the same for any given simulation 
# (for example, temperature) are consistent for both VM and NM fish 
# when the two are added together to find total fish C flux for that simulation
nsims = 1000
# pars_df <- get_pars(nsims = nsims) Commented out because we do not want to 
# re-run pars_df, but rather use the same pars as used previously 
# for VM fish MC analysis where possible

C_t_bar_nsims_NM <- rep(NA, times = nsims)
q_nsims <- rep(NA, times = nsims)
cal_nsims <- rep(NA, times = nsims)
C_flux_site_nsims_NM <- rep(NA, times = nsims)
tau_l <- rep(NA, times = nl) # nl has already been generated above

for (i in 1:nsims){
  # for Monte Carlo analysis: add new column to MC_results_NM with C flux at study site (step 11 below)
  
  # step 2 above: load data
  thedata <- load_data()
  fishdata <- thedata[[1]]
  volumedata <- thedata[[2]]
  
  # step 3 above: choose taxon
  taxagroup <- "Gonostomatidae"
  
  # step 4 above: assign parameters (does not include q and catch)
  pars.draw.i.df <- t(pars_df[i,])
  pars.draw.i <- setNames(split(pars.draw.i.df, seq(nrow(pars.draw.i.df))),
                          rownames(pars.draw.i.df))
  
  # step 5 above: filter data by taxon group
  taxadata <- dplyr::filter(thedata[[1]], Family == taxagroup)
  
  # step 6 above: calculate length bins and P(l)
  # P(l) is the probability of fish being in each length bin
  Pl_and_l <- make_Pl(taxadata$Std_length_mm)
  
  nl <- length(Pl_and_l$L)
  
  # step 7 above: For each L, calculate tau (total carbon flux for that length fish)
  # tau_l <- rep(NA, times = nl) <- removed this line and placed outside of loop
  for (j in 1:nl) {
    tau_l[j] <- make_tau(L = Pl_and_l$L[j], pars = pars.draw.i, taxagroup = taxagroup, VM = FALSE, lwreg)[4] +
      make_tau(L = Pl_and_l$L[j], pars = pars.draw.i, taxagroup = taxagroup, VM = FALSE, lwreg)[5] + 
      make_tau(L = Pl_and_l$L[j], pars = pars.draw.i, taxagroup = taxagroup, VM = FALSE, lwreg)[6]
  }
  
  # step 8 above: Multiply P(L) times tau_l and sum
  ind_C_flux <- sum(tau_l * Pl_and_l$P)
  
  # step 9 above: find average of all tows, but instead of using tows from
  # the data with calc_C_t_bar() like we did for nominal par calculation, 
  # now use make_random_catch() to draw tows from the PDF for catches
  C_t <- make_random_catch(fishdata = fishdata, volumedata = volumedata, 
                           towlist = c(2, 4, 6, 8, 9, 11, 48, 90), group = "Gonostomatidae")
  C_t_bar <- mean(C_t) # average across all simulated catches
  C_t_bar_nsims_NM[i] <- C_t_bar
  
  # step 10 above: calculate n_g for VM fish 
  # n_g = number of fish of that taxonomic group, based now on a simulated C_t_bar for myctophids
  # generate a random draw for capture efficiency for this single set of pars
  # allow capture efficiency to vary between 5% and 50%
  q <- runif(n = 1, min = 0.05, max = 0.50)
  q_nsims[i] <- q
  cal <- runif(n = 1, min = 1, max = 1.5)
  cal_nsims[i] <- cal
  n_g_myct <- calc_n_g(catch = C_t_bar_nsims_NM[i], capture_efficiency = q_nsims[i], cal = cal_nsims[i])
  
  # step 11 above: calculate C flux for NM fish and (new for MC analysis) add to MC_results_NM df
  C_flux_site_nsims_NM[i] <- ind_C_flux * n_g_myct 
}

MC_results_NM_eg_ex_mort <- cbind(pars_df, C_t_bar_nsims_NM, q_nsims, cal_nsims, C_flux_site_nsims_NM)



# repeat for resp flux of NM fish

C_t_bar_nsims_NM <- rep(NA, times = nsims)
q_nsims <- rep(NA, times = nsims)
cal_nsims <- rep(NA, times = nsims)
C_flux_site_nsims_NM <- rep(NA, times = nsims)
tau_l <- rep(NA, times = nl) # nl has already been generated above

for (i in 1:nsims){
  # for Monte Carlo analysis: add new column to MC_results_NM with C flux at study site (step 11 below)
  
  # step 2 above: load data
  thedata <- load_data()
  fishdata <- thedata[[1]]
  volumedata <- thedata[[2]]
  
  # step 3 above: choose taxon
  taxagroup <- "Gonostomatidae"
  
  # step 4 above: assign parameters (does not include q and catch)
  pars.draw.i.df <- t(pars_df[i,])
  pars.draw.i <- setNames(split(pars.draw.i.df, seq(nrow(pars.draw.i.df))),
                          rownames(pars.draw.i.df))
  
  # step 5 above: filter data by taxon group
  taxadata <- dplyr::filter(thedata[[1]], Family == taxagroup)
  
  # step 6 above: calculate length bins and P(l)
  # P(l) is the probability of fish being in each length bin
  Pl_and_l <- make_Pl(taxadata$Std_length_mm)
  
  nl <- length(Pl_and_l$L)
  
  # step 7 above: For each L, calculate tau (total carbon flux for that length fish)
  # tau_l <- rep(NA, times = nl) <- removed this line and placed outside of loop
  for (j in 1:nl) {
    tau_l[j] <- make_tau(L = Pl_and_l$L[j], pars = pars.draw.i, taxagroup = taxagroup, VM = FALSE, lwreg)[2] +
      make_tau(L = Pl_and_l$L[j], pars = pars.draw.i, taxagroup = taxagroup, VM = FALSE, lwreg)[3]
  }
  
  # step 8 above: Multiply P(L) times tau_l and sum
  ind_C_flux <- sum(tau_l * Pl_and_l$P)
  
  # step 9 above: find average of all tows, but instead of using tows from
  # the data with calc_C_t_bar() like we did for nominal par calculation, 
  # now use make_random_catch() to draw tows from the PDF for catches
  C_t <- make_random_catch(fishdata = fishdata, volumedata = volumedata, 
                           towlist = c(2, 4, 6, 8, 9, 11, 48, 90), group = "Gonostomatidae")
  C_t_bar <- mean(C_t) # average across all simulated catches
  C_t_bar_nsims_NM[i] <- C_t_bar
  
  # step 10 above: calculate n_g for VM fish 
  # n_g = number of fish of that taxonomic group, based now on a simulated C_t_bar for myctophids
  # generate a random draw for capture efficiency for this single set of pars
  # allow capture efficiency to vary between 5% and 50%
  q <- runif(n = 1, min = 0.05, max = 0.50)
  q_nsims[i] <- q
  cal <- runif(n = 1, min = 1, max = 1.5)
  cal_nsims[i] <- cal
  n_g_myct <- calc_n_g(catch = C_t_bar_nsims_NM[i], capture_efficiency = q_nsims[i], cal = cal_nsims[i])
  
  # step 11 above: calculate C flux for NM fish and (new for MC analysis) add to MC_results_NM df
  C_flux_site_nsims_NM[i] <- ind_C_flux * n_g_myct 
}

MC_results_NM_resp <- cbind(pars_df, C_t_bar_nsims_NM, q_nsims, cal_nsims, C_flux_site_nsims_NM)



## Carbon sequestration calculations based on Siegel et al. 2021 output ####

# find min/max range for resp flux for VM fish at 200 m
VM_flux_200_resp_range_from_MC <- signif(quantile(MC_results_VM_resp$C_flux_site_nsims, probs=c(.05,.95)))
min_VM_flux_200_resp_from_MC <- VM_flux_200_resp_range_from_MC[1]
max_VM_flux_200_resp_from_MC <- VM_flux_200_resp_range_from_MC[2]

# find mix/max range for eg/ex/mort flux for VM fish at 200 m
VM_flux_200_eg_ex_mort_range_from_MC <- signif(quantile(MC_results_VM_eg_ex_mort$C_flux_site_nsims, probs=c(.05,.95)))
min_VM_flux_200_eg_ex_mort_from_MC <- VM_flux_200_eg_ex_mort_range_from_MC[1]
max_VM_flux_200_eg_ex_mort_from_MC <- VM_flux_200_eg_ex_mort_range_from_MC[2]

# see FractSeqAtPAP_funcZandT_HM_calculations for output from Siegel et al. 2021
# in terms of proportion of carbon sequestered for 100 years at the PAP study site
# (lat/long of 71 and 173) of that which is released at 200 m (e.g., from respiration)
frac_seq_200m <- 0.048


# min C sequestration from VM fish at 200 m from non-egestion flux: 
min_VM_fish_flux_200m_resp_seq <- min_VM_flux_200_resp_from_MC * frac_seq_200m

# max C seq from VM fish at 200 m from non-egestion flux:
max_VM_fish_flux_200m_resp_seq <- max_VM_flux_200_resp_from_MC * frac_seq_200m
# This is the max VM fish flux at 200 m that is 
# respired (resp or SDA flux) and ~5% will be sequestered for 100 years 
## (this flux is respired CO2 and thus cannot sink below the flux boundary)

min_VM_fish_flux_200m_eg_ex_mort_seq <- min_VM_flux_200_eg_ex_mort_from_MC * 0.10
# this is the min egestion, excretion and mortality flux sequestered
# see table B.1. for more details, but note that we allow 
# the % that sinks below the flux boundary to vary from 50-90% in MC simulations, and 
# we allow the % of mortality flux that ends up below the flux boundary to vary from 40-90%, 
# and that excretion flux from excreted DIC is very small. We will assume here that
# at least 10% of this carbon could sink deep enough to be sequestered (and, below, 
# as much as 50% will sink deep enough to be sequestered) 

max_VM_fish_flux_200m_eg_ex_mort_seq <- max_VM_flux_200_eg_ex_mort_from_MC * 0.50 # we will assume here that 50% of this 
# max C flux from egestion, excretion and mortality ends up much deeper than the 
# flux boundary where this flux is calculated due to sinking (or for predation, swimming)



# do the same for NM fish at 200 m
NM_flux_200_resp_range_from_MC <- signif(quantile(MC_results_NM_resp$C_flux_site_nsims, probs=c(.05,.95)))
min_NM_flux_200_resp_from_MC <- NM_flux_200_resp_range_from_MC[1]
max_NM_flux_200_resp_from_MC <- NM_flux_200_resp_range_from_MC[2]

NM_flux_200_eg_ex_mort_range_from_MC <- signif(quantile(MC_results_NM_eg_ex_mort$C_flux_site_nsims, probs=c(.05,.95)))
min_NM_flux_200_eg_ex_mort_from_MC <- NM_flux_200_eg_ex_mort_range_from_MC[1]
max_NM_flux_200_eg_ex_mort_from_MC <- NM_flux_200_eg_ex_mort_range_from_MC[2]



min_NM_fish_flux_200m_resp_seq <- min_NM_flux_200_resp_from_MC * frac_seq_200m
max_NM_fish_flux_200m_resp_seq <- max_NM_flux_200_resp_from_MC * frac_seq_200m # max NM fish flux at 200 m from respiration
min_NM_fish_flux_200m_eg_ex_mort_seq <- min_NM_flux_200_eg_ex_mort_from_MC * .10 # min egestion, excretion and mortality flux
max_NM_fish_flux_200m_eg_ex_mort_seq <- max_NM_flux_200_eg_ex_mort_from_MC * .50 # we will assume here that 50% of this is sequestered


# sum VM and NM results to find feasible min and max C sequestration estimates at 200 m (for 100 years storage time)
min_fish_seq_200m <- min_VM_fish_flux_200m_resp_seq + min_VM_fish_flux_200m_eg_ex_mort_seq + 
  min_NM_fish_flux_200m_resp_seq + min_NM_fish_flux_200m_eg_ex_mort_seq
max_fish_seq_200m <- max_VM_fish_flux_200m_resp_seq + max_VM_fish_flux_200m_eg_ex_mort_seq + 
  max_NM_fish_flux_200m_resp_seq + max_NM_fish_flux_200m_eg_ex_mort_seq

print(c(min_fish_seq_200m, max_fish_seq_200m))

# approximately 0.125 to 6.28 mg C m^-2 d^-1  
# could be stored for 100 years. The minimum value uses the min estimate of flux pathways that can 
# sink carbon deeper than the depth of release (but not 100% of this will be sequestered, so 
# we allow this proportion of non-respiratory carbon that is sequestered to vary from 10-50%). 
# For respiratory carbon, we use the sequestration proportion for 100 years 
# suggested by Siegel et al. 2021.
# For respiratory carbon, the maximum is if ~5% of non-egestion carbon injected at this depth were stored for 100 years
# plus the upper estimate of egestion, excretion and mortality flux (that is, if 50% of 
# the carbon from these flux pathways sunk deep enough that it was sequestered)

# carbon flux estimates were 1.6 to 21 mg C m^-2 d^-1. If carbon flux is at the higher end of the 
# feasible range, we'd expect that carbon sequestration might be near the upper range as well 
# as the maximum carbon flux values were used in that calculation. So, carbon sequestration at 200 m
# could be anywhere from about 30% (6.28/21) to ~8% (0.125/1.6) of the carbon flux estimated to 200 m

# repeat for 500 m flux boundary (from Siegel et al., at 500 m, 
# approximately 53%, see FractSeqAtPAP_funcAandT_HM_calculations for 
# interpolation at 500 m)

frac_seq_500m <- 0.053

# calculate for VM fish at 500 m 
VM_flux_500_resp_range_from_MC <- signif(quantile(MC_results_VM_resp$C_flux_site_nsims, probs=c(.05,.95)))
min_VM_flux_500_resp_from_MC <- VM_flux_500_resp_range_from_MC[1]
max_VM_flux_500_resp_from_MC <- VM_flux_500_resp_range_from_MC[2]

VM_flux_500_eg_ex_mort_range_from_MC <- signif(quantile(MC_results_VM_eg_ex_mort$C_flux_site_nsims, probs=c(.05,.95)))
min_VM_flux_500_eg_ex_mort_from_MC <- VM_flux_500_eg_ex_mort_range_from_MC[1]
max_VM_flux_500_eg_ex_mort_from_MC <- VM_flux_500_eg_ex_mort_range_from_MC[2]

min_VM_fish_flux_500m_resp_seq <- min_VM_flux_500_resp_from_MC * frac_seq_500m
max_VM_fish_flux_500m_resp_seq <- max_VM_flux_500_resp_from_MC * frac_seq_500m # max VM fish flux at 500 m from respiration
min_VM_fish_flux_500m_eg_ex_mort_seq <- min_VM_flux_500_eg_ex_mort_from_MC * .10 # min egestion, excretion and mortality flux
max_VM_fish_flux_500m_eg_ex_mort_seq <- max_VM_flux_500_eg_ex_mort_from_MC * .50 # we will assume here that 50% of this is sequestered

# calculate same for NM fish at 500 m

NM_flux_500_resp_range_from_MC <- signif(quantile(MC_results_NM_resp$C_flux_site_nsims, probs=c(.05,.95)))
min_NM_flux_500_resp_from_MC <- NM_flux_500_resp_range_from_MC[1]
max_NM_flux_500_resp_from_MC <- NM_flux_500_resp_range_from_MC[2]

NM_flux_500_eg_ex_mort_range_from_MC <- signif(quantile(MC_results_NM_eg_ex_mort$C_flux_site_nsims, probs=c(.05,.95)))
min_NM_flux_500_eg_ex_mort_from_MC <- NM_flux_500_eg_ex_mort_range_from_MC[1]
max_NM_flux_500_eg_ex_mort_from_MC <- NM_flux_500_eg_ex_mort_range_from_MC[2]



min_NM_fish_flux_500m_resp_seq <- min_NM_flux_500_resp_from_MC * frac_seq_500m
max_NM_fish_flux_500m_resp_seq <- max_NM_flux_500_resp_from_MC * frac_seq_500m # max NM fish flux at 500 m from respiration
min_NM_fish_flux_500m_eg_ex_mort_seq <- min_NM_flux_500_eg_ex_mort_from_MC * .10 # min egestion, excretion and mortality flux
max_NM_fish_flux_500m_eg_ex_mort_seq <- max_NM_flux_500_eg_ex_mort_from_MC * .50 # we will assume here that 50% of this is sequestered


# sum VM and NM results to find feasible min and max C sequestration estimates at 500 m (for 100 years storage time)
min_fish_seq_500m <- min_VM_fish_flux_500m_resp_seq + min_VM_fish_flux_500m_eg_ex_mort_seq + 
  min_NM_fish_flux_500m_resp_seq + min_NM_fish_flux_500m_eg_ex_mort_seq
max_fish_seq_500m <- max_VM_fish_flux_500m_resp_seq + max_VM_fish_flux_500m_eg_ex_mort_seq + 
  max_NM_fish_flux_500m_resp_seq + max_NM_fish_flux_500m_eg_ex_mort_seq

print(c(min_fish_seq_500m, max_fish_seq_500m))

# at 500m, 5th percentile was 0.13 and 95th percentile was 6.4.
# (quite similar as for 200 m, given profile of c seq for 100 years at this location, 
# potentially due to deep winter mixing here) 


# carbon flux estimates at 500 m were 0.132 to 6.38 mg C m^-2 d^-1. Carbon transport rates
# at 500 m were about 0.51-9.6 mg C m^-2 d^-1. So, carbon sequestration at 500 m
# could be anywhere from about 66% (6.38/9.6) to ~25% (0.132/.52) of the carbon flux estimated to 500 m


## Back of the envelope calculation for comparison to Pinti et al 2023 #####

# comparison of results to Pinti et al 2023
# In Table 1, mesopelagic fish "inject" (in our paper, the same as export)
# 0.5 Pg C/yr from respiration, 0.3 from egestion (fecal), 0.06 from deadfall, 
# and 0.2 from other losses. This equals 
0.5+0.3+0.06+0.2 # 1.06 Pg C/yr, globally. 

# Then, in Fig. S10 of Pinti et al 2023, they break these values down by region. 
# In the North Atlantic, respiration export = 0.07 Pg C/yr, fecal pellet export 
# = 0.07 Pg C/yr, deadfall export = 0.02 Pg C/yr, and other losses = 0.04 Pg C/yr.
# This equals
0.07+0.07+0.02+0.04 # 0.2 Pg C/yr, in the North Atlantic (roughly 20% of global total above)
# Note that there are large uncertainties around this nominal estimate, as shown in the
# Pinti et al 2023 sensitivity analyses. 

# In any case, if our study site is representative of the North Atlantic's annual
# mesopelagic fish carbon flux, then we can compare our results to the Pinti et al 2023. 
# our C export by mesopelagic fishes (preliminary results, ** update later if needed):
# 2.3 - 31 mg C m-2 d-1 to 200 m depth, and 0.73 - 14 mg C m-2 d-1 to 500 m

# If NA as defined in Pinti et al is about 10% of global area (from Pinti et al 2023 Fig. S10, looks like
# VERY roughly 10%), 10% of global ocean surface area = 0.10*360 million km^2 = 
0.1*360000000 # 3.6e7 km^2

# our min C flux for entire North Atlantic, for mesopelagic fishes, at 200 m (comparable
# to Pinti et al 2023 definition of export as passing through euphotic zone) 
# (2.3 mg C m-2 d-1) * (1e6 m^2/km) * (365 d/yr) * (1e-18 Pg/mg) * (1.8e7 km^2 in North Atlantic) =
2.3 * 1e6 * 365 * 1e-18 * 3.6e7  # 0.03 Pg C/yr in entire N Atlantic from our study

# note this is nearly an order of magnitude lower than Pinti et al 2023 North Atlantic estimate

# our max C flux for entire North Atlantic, for mesopelagic fishes, at 200 m 
# (31 mg C m-2 d-1) * (1e6 m^2/km) * (365 d/yr) * (1e-18 Pg/mg) * (1.8e7 km^2 in North Atlantic) =
31 * 1e6 * 365 * 1e-18 * 3.6e7  # 0.4 Pg C/yr in entire N Atlantic from our study

# Note that this is about double of Pinti et al 2023 nominal estimate for North Atlantic



